version: 2

models:
  - name: female_list_view
    description: 'List of females'
    columns:
      - name: id
      - name: first_name
      - name: last_name
      - name: email
      - name: gender
      - name: ip_address
  - name: male_list_view
    description: 'List of males'
    columns:
      - name: id
      - name: first_name
      - name: last_name
      - name: email

sources:
  - name: source_jaffle_shop

    loaded_at_field: "date_added::timestamp"

    tables:
      - name: source_people # this will use the freshness defined above
