
version: 2

models:

  - name: source_ref
    description: "A starter dbt model"

sources:
  - name: filialinfo
    # schema: dbt_testing
    tables:
      - name: my_source
        description: Fiscal registers in filials table
        columns:
          - name: id
            description: Foreign key of the filials table
          - name: first_name
            description: Fiscal register ID
          - name: last_name
            description: Fiscal register number
          - name: gender
            description: modified datetime
          - name: ip_address
            description: Fiscal register type
