version: 2

sources:
  - name: my_source
    database: dbt
    schema: dbt_testing
    tables:
      - name: raw_people_list

models:
  - name: even_id_table
    access: public
    config: 
      group: some_group
      contract:
        enforced: true
      materialized: table
      unique_key: id
    description: "Table with full names"
    columns:
      - name: id
        data_type: integer  
        constraints:
          - type: primary_key
          - type: not_null
      - name: first_name
        data_type: text
      - name: last_name
        data_type: text
      - name: email
        data_type: text
      - name: gender
        data_type: text
      - name: ip_address
        data_type: text

  - name: clean_table
    access: public
    config: 
      group: some_group
      contract:
        enforced: false
      materialized: incremental
      on_schema_change: append_new_columns
      unique_key: id
    description: "Table of even id values only"
    columns:
      - name: id
        # data_type: integer
        constraints:
          - type: foreign_key
            expression: dbt_testing.even_id_table (id)
      - name: full_name
        # data_type: text
      - name: email
        # data_type: text
      - name: gender
        # data_type: text
      - name: ip_address
        # data_type: text
