version: 2

sources:
  - name: my_source
    database: dbt
    schema: dbt_testing
    tables:
      - name: raw_people_list

models:
  - name: clean_table
    # access: public
    # config: 
    #   group: some_group  # explicit opt-in
    # description: "Table with full names"
    # columns:
    #   - name: full_name
    #     description: "This is the concatenated first and last names."
    #     tests:
    #       - not_null
  - name: even_id_table
    # access: public
    # config: 
    #   group: some_group  # explicit opt-in
    # description: "Table of even id values only"
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     tests:
    #       - not_null
