version: 2

models:
  - name: clean_table
    description: "Table with full names"
    columns:
      - name: full_name
        description: "This is the concatenated first and last names."
        tests:
          - not_null